This error log was created at UTC: 1610069346.793073(2021-01-07 18:29:06(MDT)).


====================================================================
An ERROR happend while handling an order: '1610069461991' at 2021-01-07 18:32:27.991755
====================================================================



====================================================================
An ERROR happend while handling an order: dictionary changed size during iteration at 2021-01-07 18:33:48.751067
====================================================================



====================================================================
An ERROR happend while handling an order: list index out of range at 2021-01-07 18:40:15.162188
====================================================================



====================================================================
An ERROR happend while handling an order: dictionary changed size during iteration at 2021-01-07 18:47:15.569572
====================================================================

